name: test

on: 
  push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun Package Manager
        uses: oven-sh/setup-bun@v2

      - name: Install Project Dependencies
        run: bun install

      - name: Generate Prisma Client
        run: |
          cd test
          bunx prisma generate

      - name: Run Test Suite
        env:
          REDIS_SERVICE_URI: ${{ secrets.REDIS_SERVICE_URI }}
          POSTGRES_SERVICE_URI: ${{ secrets.POSTGRES_SERVICE_URI }}
        run: bun test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
